bookcase/books/urls.py
from django.urls import path
from books.views import ListBookView, CreationBookView, DeleteBookView, UpdateBookView, DetailBookView, BasketListView, \
    SetBookToLoanedView, DeleteFromBasketView, AddOrRemoveFromBasketView, LoanedByUserView, UserGiveBackBookView, \
    GiveBackAllOrSelectedUserBooks

urlpatterns = [
    path('', ListBookView.as_view(), name='home'),
    path('addbook', CreationBookView.as_view(), name='addbook'),
    path('deletebook/<pk>', DeleteBookView.as_view(), name='deletebook'),
    path('updatebook/<pk>', UpdateBookView.as_view(), name='updatebook'),
    path('detailbook/<pk>/', DetailBookView.as_view(), name='detailbook'),
    path('add_to_basket', AddOrRemoveFromBasketView.as_view(), name='addtobasket'),
    path('basketuser:<pk>', BasketListView.as_view(), name='basketlist'),
    path("delete_from_basket", DeleteFromBasketView.as_view(), name='deletefrombasket'),
    path('set_loaned', SetBookToLoanedView.as_view(), name="setloaned"),
    path('userbooks', LoanedByUserView.as_view(), name='userbooks'),
    path('usergivebackbook', UserGiveBackBookView.as_view(), name='usergivebackbook'),
    path('usergivebackallbooks', GiveBackAllOrSelectedUserBooks.as_view(), name='usergivebackmanybooks')
]

bookcase/config/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import ViewLogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('books.urls')),
    path('login/', ViewLogin.as_view(), name='login'),
    path('accounts/', include('allauth.urls')),
]

bookcase/books/models.py
import uuid
from django.db import models
from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase, Tag
from django.utils.translation import ugettext_lazy
from users.models import CustomUser


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    tag = models.ForeignKey(Tag, related_name="uuid_tagged_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ugettext_lazy("Tag")
        verbose_name_plural = ugettext_lazy("Tags")


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    publisher = models.CharField(max_length=100)
    tags = TaggableManager(through=UUIDTaggedItem)
    is_loaned = models.BooleanField(default=False)
    loaned_date = models.DateField(null=True, blank=True)
    loaner_user = models.ForeignKey('users.CustomUser', models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title


class UserBasket(models.Model):
    basket_id = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True)
    user_id = models.ForeignKey('users.CustomUser', models.SET_NULL, null=True)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.user_id.__str__()

bookcase/books/forms.py
from crispy_forms.bootstrap import PrependedText, AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from django.forms import ModelForm
from books.models import Book


class CreateBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'publisher', 'tags', ]

    def __init__(self, *args, **kwargs):
        super(CreateBookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(Field('author', placeholder="Author"),
                                    Field('title', placeholder="Title"),
                                    Field('publisher', placeholder="Publisher"),
                                    Field('tags', placeholder="Tags"),
                                    Submit('submit', 'Add book', css_class='btn btn-info'),)


class UpdateBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'publisher', 'tags', ]

    def __init__(self, *args, **kwargs):
        super(UpdateBookForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(Field('author', placeholder="Author"),
                                    Field('title', placeholder="Title"),
                                    Field('publisher', placeholder="Publisher"),
                                    Field('tags', placeholder="Tags"),
                                    Submit('submit', 'Edit book', css_class='btn btn-info'), )

bookcase/books/views.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView, RedirectView
from books.forms import CreateBookForm, UpdateBookForm
from books.models import Book, UserBasket


class CheckBasketMixin:
    def get_context_data(self, **kwargs):
        context = super(CheckBasketMixin, self).get_context_data()
        context['is_userbasket_exist'] = self.is_userbasket_exist(self.request.user)
        return context

    def is_userbasket_exist(self, user):
        basket = UserBasket.objects.filter(user_id=user).exists()
        return basket


class CheckIfLoggedMixin(LoginRequiredMixin):
    login_url = reverse_lazy('login')


class ListBookView(CheckIfLoggedMixin, CheckBasketMixin, ListView):
    model = Book
    template_name = 'books/booklist.html'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('search')
        if not query:
            return Book.objects.all().order_by('title')
        object_list = Book.objects.filter(
            Q(tags__name__icontains=query) | Q(title__icontains=query) | Q(author__icontains=query) |
            Q(publisher__icontains=query)).distinct()
        return object_list.order_by('title')


class AddOrRemoveFromBasketView(RedirectView):
    def post(self, request, *args, **kwargs):
        if request.is_ajax:
            book = Book.objects.get(id=request.POST.get('book_id'))
            basket = UserBasket.objects.filter(user_id=request.user).first()
            if not basket:
                create_basket = UserBasket.objects.create(user_id=request.user)
                create_basket.books.add(book)
                create_basket.save()
                return JsonResponse({"success": True})
            if not book.userbasket_set.filter(user_id=basket.user_id).exists():
                basket.books.add(book)
            else:
                basket.books.remove(book)
            basket.save()
            if basket.books.count() == 0:
                basket.delete()
            return JsonResponse({"success": True})
        return JsonResponse({'success': False})


class BasketListView(CheckIfLoggedMixin, CheckBasketMixin, ListView):
    model = UserBasket
    template_name = 'books/basketlist.html'

    def get_queryset(self):
        basket_list = UserBasket.objects.filter(Q(user_id=self.request.user))
        return basket_list


class DeleteFromBasketView(RedirectView):
    def post(self, request, *args, **kwargs):
        if request.is_ajax:
            book = Book.objects.get(id=request.POST.get('book_id'))
            basket = UserBasket.objects.get(user_id=request.user)
            basket.books.remove(book)
            if basket.books.count() == 0:
                basket.delete()
            return JsonResponse({"success": True})
        return JsonResponse({"success": False})


class SetBookToLoanedView(CheckIfLoggedMixin, RedirectView):
    def get(self, request, **response_kwargs):
        basket = UserBasket.objects.filter(user_id=request.user).first()
        if basket:
            books_in_basket = basket.books.all()
            for book in books_in_basket:
                if book.is_loaned == True:
                    return redirect("basketlist", pk=request.user.id)
            for book in books_in_basket:
                book.is_loaned = True
                book.loaned_date = datetime.date.today()
                book.loaner_user = request.user
                book.save()
            basket.delete()
        return redirect("home")


class GiveBackAllOrSelectedUserBooks(CheckIfLoggedMixin, RedirectView):
    def get(self, request, *args, **kwargs):
        query = self.request.GET.getlist('whichbookreturn')
        if not query:
            userbooks = Book.objects.filter(Q(loaner_user=self.request.user))
            for book in userbooks:
                book.is_loaned = False
                book.loaned_date = None
                book.loaner_user = None
                book.save()
        for bookid in query:
            book_checked_to_return = Book.objects.get(id=bookid)
            book_checked_to_return.is_loaned = False
            book_checked_to_return.loaned_date = None
            book_checked_to_return.loaner_user = None
            book_checked_to_return.save()
        return redirect("userbooks")


class CreationBookView(CheckIfLoggedMixin, CheckBasketMixin, CreateView):
    form_class = CreateBookForm
    success_url = reverse_lazy('home')
    template_name = 'books/createbook.html'


class DeleteBookView(CheckIfLoggedMixin, CheckBasketMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('home')
    template_name = 'books/deletebook.html'


class UpdateBookView(CheckIfLoggedMixin, CheckBasketMixin, UpdateView):
    model = Book
    form_class = UpdateBookForm
    success_url = reverse_lazy('home')
    template_name = 'books/updatebook.html'


class DetailBookView(CheckIfLoggedMixin, CheckBasketMixin, DetailView):
    model = Book
    template_name = 'books/detailbook.html'


class LoanedByUserView(CheckIfLoggedMixin, CheckBasketMixin, ListView):
    model = Book
    template_name = 'books/userbookslist.html'

    def get_queryset(self):
        book = Book.objects.filter(Q(loaner_user=self.request.user))
        return book


class UserGiveBackBookView(RedirectView):
    def post(self, request, *args, **kwargs):
        if request.is_ajax:
            book = Book.objects.get(id=request.POST.get('book_id'))
            book.is_loaned = False
            book.loaned_date = None
            book.loaner_user = None
            book.save()
            return JsonResponse({"success": True})
        return JsonResponse({"success": False})

bookcase/books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/books.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <title>
        {% block title %}{% endblock %}
    </title>
    <style>
    </style>
</head>
{% csrf_token %}
<body class="bg-light">
<header class="shadow bg-dark text-white row mb-4 p-2">
    <h3 class="font-weight-light text-center col-2 m-auto">
        <a href="{% url 'home' %}" class="text-white text-decoration-none"><i class="fa fa-book-reader mr-1"></i>Bookcase</a>
    </h3>
    <form action="{% url 'home' %}" method="get" class="col-6 m-auto">
        <div class="input-group">
            <input name="search" type="text" class="form-control"
                   placeholder="Search book by author, title, publisher, tags... "/>
            <div class="input-group-append">
                <button type="submit" class="btn btn-info"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>
    <div class="col-2 text-center m-auto">
        <div class="dropdown">
            <button type="button" class="btn btn-dark dropdown-toggle text-muted m-auto" data-toggle="dropdown">
                {{user.username}}
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'userbooks' %}">Your books</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </div>
    {% if is_userbasket_exist == False %}
    <a class="col-1 m-auto btn btn-dark disabled" href="{% url 'basketlist' user.id %}" id="userbasket"
       data-toggle="tooltip" title="Your basket">
        {% else %}
        <a class="col-1 m-auto btn btn-dark" href="{% url 'basketlist' user.id %}" id="userbasket" data-toggle="tooltip"
           title="Your basket">
            {% endif %}
            <i class="fa fa-shopping-basket h4 m-auto"></i>
        </a>
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<script>
{% block javascript %}
{% endblock %}
</script>
</body>
</html>

bookcase/books/templates/books/basketlist.html
{% extends 'books/base.html' %}
{% block title %}Basket{% endblock %}
{% block javascript %}
{% endblock %}
{% block content %}
{% csrf_token %}
<div class="p-4 m-auto h5">
    <p class="text-center">Your basket</p>
    <table class="table shadow bg-white rounded">
        {% for object in object_list %}
        <thead>
        <tr>
            <th scope="col">Author</th>
            <th scope="col">Title</th>
            <th scope="col">Publisher</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for books in object.books.all %}
        {% if books.is_loaned == True %}
        <tr>
            <th colspan="4" data-loaned="true" class="text-danger text-center warning">
                Book: "{{ books.title }}" has been already borrowed by another user. Please remove it from the basket
            </th>
        </tr>
        <tr class="text-muted">
            {% else %}
        <tr>
            {% endif %}
            <th>{{books.author}}</th>
            <th data-catid="{{ books.id }}" class="details">{{books.title}}</th>
            <th>{{books.publisher}}</th>
            <th>
                <span class="btn btn-danger deletefrombasket" data-catid="{{books.id}}" data-toggle="tooltip"
                      title="Delete from basket">
                    <i class="fa fa-minus-circle"></i>
                </span>
            </th>
        </tr>
        </tbody>
        {% endfor %}
    </table>
    <a href="{% url 'setloaned' %}" class="btn btn-info borrow" data-toggle="tooltip" title="Borrow book!">Borrow</a>
    {% empty %}
    <p class="text-center"> Your basket has been deleted </p>
    {% endfor %}
</div>
{% endblock %}

bookcase/books/templates/books/booklist.html
{% extends 'books/base.html' %}
{% block title %}Books list{% endblock %}
{% block javascript %}
{% endblock %}
{% load filter %}
{% block content %}
{% csrf_token %}
<div class="p-4 m-auto h5 font-weight-light">
    {% if user.is_superuser == True %}
    <a href="{% url 'addbook' %}" class="btn btn-info text-white text-decoration-none m-2"><i
            class="fa fa-plus-square mr-2"></i>ADD BOOK</a>
    {% endif %}
    <div class="shadow bg-white rounded">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Author</th>
                <th scope="col">Title</th>
                <th scope="col">Publisher</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
                {% if perms.books.delete_book %}
                <th scope="col"></th>
                {% endif %}
                {% if perms.books.change_book %}
                <th scope="col"></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for book in page_obj %}
            <tr>
                <th>{{ book.author }}</th>
                <th data-catid="{{ book.id }}" class="details">{{ book.title}}</th>
                <th>{{ book.publisher }}</th>
                {% if book.userbasket_set|userbasket:user.id %}
                <th>
                    <span class="text-warning font-weight-normal" id="status{{ book.id }}">In basket</span>
                </th>
                <th>
                    <span class="basket btn btn-warning disabled" data-toggle="tooltip" title="In basket"
                          data-catid="{{ book.id }}" id="basket{{ book.id }}">
                        <i class="fa fa-shopping-basket"></i>
                    </span>
                </th>
                {% elif book.is_loaned == False %}
                <th>
                    <span class="text-success font-weight-normal" id="status{{ book.id }}">Available</span>
                </th>
                <th>
                    <span class="basket btn btn-success" data-toggle="tooltip" title="Add to basket"
                          data-catid="{{ book.id }}" id="basket{{ book.id }}">
                        <i class="fa fa-shopping-basket"></i>
                    </span>
                </th>
                {% else %}
                <th>
                    <span class="status text-danger font-weight-normal">Loaned</span>
                </th>
                <th>
                    <span class="basket btn btn-danger disabled" data-toggle="tooltip" title="Add to basket">
                        <i class="fa fa-shopping-basket"></i>
                    </span>
                </th>
                {% endif %}
                {% if perms.books.delete_book %}
                <th>
                    <a href="{% url 'deletebook' book.id %}" class="btn btn-danger" data-toggle="tooltip"
                       title="Delete book">
                        <i class="fa fa-trash"></i>
                    </a>
                </th>
                {% endif %}
                {% if perms.books.change_book %}
                <th>
                    <a href="{% url 'updatebook' book.id %}" class="btn btn-info" data-toggle="tooltip"
                       title="Edit book">
                        <i class="fa fa-edit"></i>
                    </a>
                </th>
                {% endif %}
            </tr>
            </tbody>
            {% empty %}
            <tr>
                <th colspan="7" class="text-center">Empty</th>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="pagination d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.number == 1 %}
            <a href="#" class="btn btn-info disabled">&laquo; first</a>
            <a href="#" class="btn btn-info disabled">previous</a>
            {% endif %}
            {% if page_obj.has_previous %}
                <a href="?page=1" class="btn btn-info">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-info">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-info">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-info">last &raquo;</a>
            {% endif %}
            {% if page_obj.number == page_obj.paginator.num_pages %}
                <a href="#" class="btn btn-info disabled">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-info disabled">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

bookcase/books/templates/books/createbook.html
{% extends 'books/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create book{% endblock %}
{% block content %}
<div class="shadow bg-white rounded p-4 m-auto w-50 font-weight-light">
    <h3 class="text-center mb-4">Add book</h3>
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
{% endblock %}

bookcase/books/templates/books/deletebook.html
{% extends 'books/base.html' %}

{% block title %}Delete book{% endblock %}
{% block content %}
<div class="shadow bg-white rounded p-4 m-auto w-50 text-center h5 font-weight-light">
    <form method="post">
        {% csrf_token %}
        <p >Are you sure you want to delete "{{ object.title }}"?</p>
        <button type="submit" class="btn btn-danger">Delete book</button>
    </form>
</div>
{% endblock %}

bookcase/books/templates/books/detailbook.html
{% extends 'books/base.html' %}
{% block title %}Detail book{% endblock %}
{% block javascript %}
{% endblock %}
{% block content %}
{% load filter %}
{% csrf_token %}
<div class="shadow bg-white rounded p-4 m-auto w-50">
    <h3>{{ object.title }}</h3>
    <p> Author: {{ object.author }}</p>
    <p> Publisher: {{ object.publisher }}</p>
    <form action="{% url 'home' %}" method="GET">
    <p> Tags: {% for tag in object.tags.all %}
        <input type="submit" name="search" value="{{tag}}" class="btn btn-info">
        {% endfor %}
    </p>
    </form>
    <p>
        {% if object.loaner_user_id == user.id %}
        <span class="btn btn-info giveback" data-catid="{{ object.id }}" data-toggle="tooltip" title="Give back">
        <i class="fa fa-undo mr-1"></i>Return book
        </span>
        {% endif %}
        {% if book.userbasket_set|userbasket:user.id %}
        <span class="basket btn btn-warning disabled" data-toggle="tooltip" title="In basket"
              data-catid="{{ book.id }}" id="basket{{ book.id }}">
                        <i class="fa fa-shopping-basket mr-1"></i><span id="detail{{ book.id }}">In basket</span>
        </span>
        {% elif book.is_loaned == False %}
        <span class="basket btn btn-success" data-toggle="tooltip" title="Add to basket"
              data-catid="{{ book.id }}" id="basket{{ book.id }}">
                        <i class="fa fa-shopping-basket mr-1"></i><span id="detail{{ book.id }}">Available</span>
        </span>
        {% endif %}
    </p>
</div>
{% endblock %}

bookcase/books/templates/books/email.html
<p>You have to return book {{ book_title }}</p>
<p><a href="{% url 'detailbook' book_id %}\">Link to book</a></p>

bookcase/books/templates/books/updatebook.html
{% extends 'books/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Update book{% endblock %}
{% block content %}
<div class="shadow bg-white rounded p-4 m-auto w-50">
    <h3 class="text-center">Edit book</h3>
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
{% endblock %}

bookcase/books/templates/books/userbookslist.html
{% extends 'books/base.html' %}
{% block title %}Your books{% endblock %}
{% block javascript %}
{% endblock %}
{% block content %}
{% csrf_token %}
<div class="p-4 m-auto h5 font-weight-light">
    <p class="text-center">Your books</p>
    <table class="table shadow bg-white rounded">
        <thead>
        <tr>
            <th scope="col">Author</th>
            <th scope="col">Title</th>
            <th scope="col">Publisher</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <form action="{% url 'usergivebackmanybooks' %}" method="get">
            {% for object in object_list %}
            <tr>
                <th>{{object.author}}</th>
                <th data-catid="{{ object.id }}" class="details">{{object.title}}</th>
                <th>{{object.publisher}}</th>
                <th>
                <span class="btn btn-info giveback" data-catid="{{ object.id }}" data-toggle="tooltip"
                      title="Give back">
                    <i class="fa fa-undo"></i>
                </span>
                </th>
                {% if object_list.count <= 1 %}
                <th>
                    <label class="switch m-2">
                            <input class="check" type="checkbox" name="whichbookreturn" value="{{ object.id }}" disabled>
                            <span class="slider round"></span>
                        </label>
                </th>
                {% else %}
                <th>
                        <label class="switch m-2">
                            <input class="check" type="checkbox" name="whichbookreturn" value="{{ object.id }}">
                            <span class="slider round"></span>
                        </label>
                </th>
                {% endif %}
            </tr>
            {% empty %}
            <tr>
                <th colspan="4" class="text-center">Empty</th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button type="submit" class="btn btn-danger" data-toggle="tooltip" title="Return books">
        <i class="fa fa-undo mr-1"></i><span class="returnbooks">Return all books</span>
    </button>
    </form>
</div>
{% endblock %}